gettext('1. %(count) fold');
gettext('2. %(count) folds');
gettext('%(count) More Locations+');
gettext('%(count) More Sports+');
gettext('1. %(count) More Tournaments+');
gettext('2. %(count) More Tournaments+');
gettext('%(locationName) overview');
gettext('%(tournamentName) overview');
gettext('Accept any');
gettext('Accept lower');
gettext('Add picks back to betslip');
gettext('Adjust stake');
gettext('All sports');
gettext('At least one of your selection has an invalid stake');
gettext('At least one of your selection is invalid');
gettext('Available free bet');
gettext('1. Bet');
gettext('2. Bets');
gettext('Bet builder');
gettext('Bet placement failed');
gettext('Bet successfully placed');
gettext('Bet with stake %(betAmount)%(currencySymbol) was sent for manual approval');
gettext('Cash Out %(value)%(currencySymbol)');
gettext('1. Combo - %(count) selection');
gettext('2. Combo - %(count) selections');
gettext('1. Combo - 1 selection');
gettext('Confirm Cash Out %(value)%(currencySymbol)');
gettext('Event name');
gettext('Exclude this selection');
gettext('exp. %(expiryDate)');
gettext('Failed to Cash Out %(value)%(currencySymbol)');
gettext('Fav');
gettext('Go to Bet Details');
gettext('Hide selections');
gettext('Include this selection');
gettext('live');
gettext('login');
gettext('Place %(maxStake)%(currencySymbol) and sent to approval %(manualBetAmount)%(currencySymbol)');
gettext('Place %(maxStake)%(currencySymbol) instead of %(stake)%(currencySymbol)');
gettext('Popular Leagues');
gettext('register');
gettext('Send %(stake)%(currencySymbol) for manual approval');
gettext('Stake cannot exceed %(stake)%(currencySymbol)');
gettext('Stake must be at least %(stake)%(currencySymbol)');
gettext('Successfully Cashed Out %(value)%(currencySymbol)');
gettext('The selection is no longer available!');
gettext('To place a bet, %(register) or %(login) and click on any price.');
gettext('To place a bet, please click on any price.');
gettext('To return');
gettext('Total Odds');
gettext('Void');
gettext('Waiting for Cash Out %(value)%(currencySymbol)');
gettext('Won');
gettext('You do not have any bets in this category.');
gettext('You must enter a stake in order to place a bet');
gettext('You will Cash Out %(value)%(currencySymbol)');
gettext('Your betslip is empty');
gettext('/location');
gettext('1. %(count) More Location+');
gettext('2. %(count) More Locations+');
gettext('1. %(step) hour');
gettext('2. %(step) hours');
gettext('Event view');
gettext('1. hour');
gettext('2. hours');
gettext('Next events');
gettext('Please wait while your %(value) Cash Out is being processed');
gettext('View More');
gettext('Yes');
